added email

diff --git a/.github/workflows/testwf.yml b/.github/workflows/testwf.yml
--- a/.github/workflows/testwf.yml
+++ b/.github/workflows/testwf.yml
@@ -27,11 +27,13 @@ jobs:
       - name: Check for release notes
         id: check_rel_notes
         run: ls -l rel_notes.md
-        #run: ls -l ./lede-1701/rel_notes.md    
-      - name: Check for failure
-        #if: job.steps.check_rel_notes.status == failure() 
+        #run: ls -l ./lede-1701/rel_notes.md  
         if: failure()
         run: exit 1
+      #- name: Check for failure
+        #if: job.steps.check_rel_notes.status == failure() 
+      #  if: failure()
+      #  run: exit 1
 
       - name: Run shell commands
         run: |
